### ISSUE TITLE
文本重复

### ISSUE THREAD

**Issue by hotoo** [yanyiwu/blog#1]
https://github.com/yanyiwu/dwelling/blob/master/_posts/2015-03-02-the-best-show.md

周星驰《我演的最好的一场戏》

> 虽然我演戏无数，但是我要说，我最好的戏，就是七岁那年演给妈妈的这场戏。
> 
> **『下面开始重复』**
> 
> 那时，我们都正是长身体的时候，所以不管多么困难，...

**Comment by yanyiwu** [comment]
已修复，我居然没有发现，非常感谢！
